### PR TITLE
Feedback Page #70

### LINKED ISSUE #70: Add Feedback Page
Add feedback page

### PR DESCRIPTION
**Pull request by ishitakapoor26**
Fixes #70 

Screenshot:

feedback

## Checklist:

- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

### CODE REVIEW

**Comment by ishitakapoor26** [comment]
@hariramjp777 pls review pr.

**Comment by khushishikhu** [comment]
@ishitakapoor26 please add the screenshots

**Comment by hariramjp777** [comment]
Yes @ishitakapoor26, Please add screenshots in your comment.

**Comment by khushishikhu** [comment]
@ishitakapoor26 Instead of this blue. Can you change it according to the UI of our project that is in Purple.

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 Instead of this blue although it looks very nice. Can you change it according to the UI of our project that is in Purple.

I can change color of feedback box but the problem is the background color can't be changed because it is a vector image. For it to match the theme, I have to look for another vector art. Still, I'll try my best yo find relevant background...

**Comment by ishitakapoor26** [comment]
feedbackw

@khushishikhu now is it okay I've added purple gradience?

**Comment by ishitakapoor26** [comment]
@khushishikhu pls check it now. I've added purple gradience.

feedback

**Comment by khushishikhu** [comment]
Lets ask @Aaishpra @hariramjp777  what more changes can be done or this will work

**Pull request merged**
