### PR TITLE
Enhanced the about-us page

### LINKED ISSUE #83: Improvement in the UI of About Us
### 🐞 Describe the Bug

currently the UIof about us page is not so attractive. we would like to have a good UI for that.

### 💡 To Reproduce

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by coding-geek21**
## What do these changes do?

Enhanced the about-us page

## Related Issue

Fixes #83 

## Checklist:

- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video or GIF:

https://www.awesomescreenshot.com/video/4220073?key=a2167ac117931ae31ecc3fd9e24924f5

---

### CODE REVIEW

**Comment by khushishikhu** [comment]
@coding-geek21 It looks amazing!!

**Comment by coding-geek21** [comment]
> @coding-geek21 It looks amazing!!

Thanks a lot for your feedback 😍

**Review by hariramjp777 — APPROVED** [review]
Looks good @coding-geek21

**Comment by coding-geek21** [comment]
> Looks good @coding-geek21 

Thanks a lot 🤩

**Pull request merged**
