### PR TITLE
Suggestions updated.

### PR DESCRIPTION
**Pull request by MuhammadAbdullah-hash**
## What do these changes do?
I have modified the code as per your suggestions. Verification for /helper /seeker has been added and errors are routed to a separate error.html page. The signup is now routing to register/seeker page as per you suggested
## Related Issue
These fixes are related to issue number #52

### CODE REVIEW

**Comment by khushishikhu** [comment]
@MuhammadAbdullah-hash Is this the new PR of that same issue? And so we will consider this PR or the previous.

I will look into this by the end of the day

**Comment by MuhammadAbdullah-hash** [comment]
> @MuhammadAbdullah-hash Is this the new PR of that same issue? And so we will consider this PR or the previous one.
> 
> I will look into this by the end of the day

yes, it's the new PR of the same issue. Previous PR was having conflict so I made the changes again along with your suggestions which were mentioned in the last one. Kindly consider this PR

**Review by khushishikhu — APPROVED** [review]
I have tested this PR and looks perfect

**Review by hariramjp777 — CHANGES_REQUESTED** [review]
@MuhammadAbdullah-hash, `views.py` is conflicting. please fix that bro :+1:

**Pull request merged**
