### PR TITLE
User added to db under categories helper/seeker

### PR DESCRIPTION
**Pull request by MuhammadAbdullah-hash**
ISSUE #12 

## What do these changes do?
User can now signup/in as helper /seeker and they are added in a separate table named "User_status" in database. + Added function to route to the signup page and resolved an issue regarding utf encoding of activation mail.

### CODE REVIEW

**Review by khushishikhu — COMMENTED** [review]
as the PR looks good to me but I have a suggestion that both the buttons under the card is quite confusing to find out which is for helper and which is for seeker.  Make the two buttons under the navbar with name as helper and seeker. I hope you got my point

**Comment by khushishikhu** [comment]
@MuhammadAbdullah-hash also you can open another issue for changing the UI of the form( helper & seeker) which goes in contrast to the website UI. As @hariramjp777 has also uploaded the figma file for the reference

**Comment by MuhammadAbdullah-hash** [comment]
> as the PR looks good to me but I have a suggestion that both the buttons under the card is quite confusing to find out which is for helper and which is for seeker. Make the two buttons under the navbar with name as helper and seeker. I hope you got my point

the signup buttons ?

**Comment by MuhammadAbdullah-hash** [comment]
> @MuhammadAbdullah-hash also you can open another issue for changing the UI of the form( helper & seeker) which goes in contrast to the website UI. As @hariramjp777 has also uploaded the figma file for the reference

sure I will open another issue for that after solving this button thing :)

**Comment by khushishikhu** [comment]
> > as the PR looks good to me but I have a suggestion that both the buttons under the card is quite confusing to find out which is for helper and which is for seeker. Make the two buttons under the navbar with name as helper and seeker. I hope you got my point
> 
> the signup buttons ?

yes.

**Comment by MuhammadAbdullah-hash** [comment]
Signup buttons renamed and replaced under navbar 
kindly check it out

**Review by khushishikhu — APPROVED** [review]

**Pull request merged**
