### PR TITLE
Updated register page

### PR DESCRIPTION
**Pull request by AkshatSharma000**
## What do these changes do?

Given a fresh look to register page which is responsive display as well.

## Related Issue

Fixes #77 

## Checklist:

- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video or GIF:

---

### CODE REVIEW

**Comment by khushishikhu** [comment]
@AkshatSharma000 write the issue number in your PR

**Comment by hariramjp777** [comment]
@AkshatSharma000, Please add a screenshot in your comment.

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000 write the issue number in your PR. I think you are not assigned in any issue. You can not make a PR until you are assigned in any issue

So how to get assigned.

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000, Please add a screenshot in your comment.

Screenshot 2021-06-18 220429

**Comment by hariramjp777** [comment]
@AkshatSharma000, I've checked your PR, This is what you've done,

image

The registration (Signup) page is already done but It's not responsive. 
If you want to work on this page, can you please make it responsive without changing the existing design?

**Review by hariramjp777 — COMMENTED** [review]
@AkshatSharma000, I've checked your PR, This is what you've done,

image

The registration (Signup) page was already done but It was not responsive. 
If you want to work on this page, can you please make it responsive without changing the existing design?

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000, I've checked your PR, This is what you've done,
> 
> image
> 
> The registration (Signup) page is already done but It's not responsive.
> If you want to work on this page, can you please make it responsive without changing the existing design?

There is an issue with header and footer. It is not responsive but the forms is working pretty well.
The change is required in header and footer

**Comment by hariramjp777** [comment]
> > @AkshatSharma000 write the issue number in your PR. I think you are not assigned in any issue. You can not make a PR until you are assigned in any issue
> 
> So how to get assigned.

@AkshatSharma000, If you want to work on this page, Go to the issues page and create a new issue, We'll assign it to you :+1:

**Comment by hariramjp777** [comment]
Yeah @AkshatSharma000, We don't want to change our UI bro.
Here's the Figma https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1

**Comment by AkshatSharma000** [comment]
Can anyone review this??

**Comment by Aaishpra** [comment]
@hariramjp777 what's the progress here, is the UI matching to what you want?

**Comment by AkshatSharma000** [comment]
> @hariramjp777 what's the progress here, is the UI matching to what you want?

Can you just review , I have been waiting for so long.

**Pull request closed without merging**
