### PR TITLE
Added Contact Us Page

### PR DESCRIPTION
**Pull request by Shaishav0507**
Fixes: #68 
Hey @hariramjp777 @khushishikhu 
Added the contact us page.
Please check and update.
Thanks

## Related Issue

Fixes #

## Checklist:

- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you tested the code before submission?

## Screenshots or Video or GIF:

---

### CODE REVIEW

**Comment by Shaishav0507** [comment]
image
This is how it looks.
If any changes please tell me.

**Comment by khushishikhu** [comment]
@Shaishav0507 please add the screenshot

**Comment by Shaishav0507** [comment]
> @Shaishav0507 please add the screenshot

Added

**Comment by khushishikhu** [comment]
@Shaishav0507  we will think about it's UI later on till that you can work on some other issues

**Comment by Shaishav0507** [comment]
Ok

**Comment by khushishikhu** [comment]
@Shaishav0507  we will make a new issue for making it's UI better

**Review by khushishikhu — APPROVED** [review]

**Pull request merged**
