### PR TITLE
Added About Us Page

### PR DESCRIPTION
**Pull request by Shaishav0507**
Fixes: #48 
Hey @Aaishpra @khushishikhu 
I have added the about us page.
Please check and update me if any changes need to be made.
Thanks

## Related Issue

Fixes #

## Checklist:

- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video or GIF:

---

### CODE REVIEW

**Review by hariramjp777 — COMMENTED** [review]
Hi @Shaishav0507, Can you please add a screenshot (or gif) as a comment?

**Comment by Shaishav0507** [comment]
Sure

**Comment by Shaishav0507** [comment]
image

**Comment by Shaishav0507** [comment]
When it will be connected to the main directory, navbar will come, and footer will come so these white spaces won't be there.
This is just the outlet with connecting.

**Comment by Shaishav0507** [comment]
@hariramjp777 Is it ok?

**Comment by hariramjp777** [comment]
@Shaishav0507, Design could be improved bro

**Comment by Shaishav0507** [comment]
> @Shaishav0507, Design could be improved bro

Could you tell me what can be changed.
Because I have taken from the basic layout only.

**Comment by Shaishav0507** [comment]
@hariramjp777 Plus this page in zoomed out so it looks more empty.

**Comment by khushishikhu** [comment]
@hariramjp777 Please suggest some UI design that can be improved in this. As you are better in that ;)

**Comment by Shaishav0507** [comment]
> @hariramjp777 Please suggest some UI design that can be improved in this. As you are better in that ;)

Ya please suggest so that I can improve it.

**Comment by hariramjp777** [comment]
> > @hariramjp777 Please suggest some UI design that can be improved in this. As you are better in that ;)
> 
> Ya please suggest so that I can improve it.

Bro @Shaishav0507, I tell you tomorrow bro if I get any ideas.

**Comment by Shaishav0507** [comment]
@hariramjp777 no problem brother.

**Comment by khushishikhu** [comment]
@hariramjp777  Let's merge this PR. we will make another issue for improving it's UI

**Review by khushishikhu — APPROVED** [review]

**Pull request merged**
