### PR TITLE
Added fetch data from blog model

### LINKED ISSUE #152: Fetch Blog contents from model
### 🐣 Is your feature request related to a problem? Please describe.

I want to make blog functional by fetching and adding contents from blog model

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue

Added fetch data from blog model

Fixes #152 

## Checklist:

- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video or GIF:

https://www.awesomescreenshot.com/video/4535534?key=7c53ff97e70f159980a6d8ce3f674e7b

https://www.awesomescreenshot.com/video/4535613?key=a05254d653efb5fcfe5a10145f3966c4

---

@khushishikhu  Please Review this PR

### CODE REVIEW

**Comment by khushishikhu** [comment]
@coding-geek21 sorry for being not able to check your PRs I got busy in my internship. Please solve the merge conflicts. The PR looks good 🎉

**Comment by coding-geek21** [comment]
> @coding-geek21 sorry for being not able to check your PRs I got busy in my internship. Please solve the merge conflicts. The PR looks good 🎉

No problem 😊, I have resolved conflicts , Thank you!!

**Review by hariramjp777 — APPROVED** [review]

**Review by Aaishpra — APPROVED** [review]

**Comment by Aaishpra** [comment]
RESOLVE CONFLICTS then I can merge

**Comment by coding-geek21** [comment]
> RESOLVE CONFLICTS then I can merge

@Aaishpra  Resolved conflicts

**Pull request merged**
