### PR TITLE
blog page

### LINKED ISSUE #102: Design blog page
### 🐞 Describe the Bug
There were no blog page i want to design that page
@khushishikhu can i work on this issue

### PR DESCRIPTION
**Pull request by kumarishalini6**
## What do these changes do?
I have made a blog page which was not available 

Fixes #102

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khushishikhu  please have a look on this issue

**Comment by khushishikhu** [comment]
Add the screenshot

**Comment by khushishikhu** [comment]
Add the screenshot

**Comment by kumarishalini6** [comment]
https://user-images.githubusercontent.com/69043944/123919695-aa606100-d931-11eb-8c82-0c568476c9a3.mp4

it is also fully responsive .

**Comment by kumarishalini6** [comment]
> Add the screenshot

Done

**Pull request merged**
